### ISSUE TITLE
Add to PlatformIO

### ISSUE THREAD

**Issue by skorokithakis** [daknuett/cryptosuite2#5]
It would be great if this library could be added to the PlatformIO index so we could automatically add it to our projects as a dependency. This is as easy as adding a JSON file to the repo: https://docs.platformio.org/en/latest/librarymanager/creating.html#register

**Comment by daknuett** [comment]
Adding this library to PlatformIO is a great idea. 
But might it be a better idea to add the c-interface only instead of the kind of hacky Arduino interface?

I don't really know about PlatformIO, what kinds of people are there?

**Comment by skorokithakis** [comment]
Hmm, I'm not sure about the two interfaces, what do you mean?

Also, what do you mean by "kinds of people"? PlatformIO is a dependency manager/builder/general helper utility which has some very useful features, especially for building/uploading from the CLI.

**Comment by daknuett** [comment]
I added the `library.json` in  6ac80ba. It is on a new branch for now. I have registered the library but waiting for moderation. Once the library is sucessfully registered I wil merge the changes into master.

cryptosuite2 has two interfaces: A `C++` wrapper for the Arduino users and a full `C` API that allows to reduce memory usage and brings more functions. The `C++` wrapper is designed as a drop-in replacement for [cryptosuite](https://github.com/Cathedrow/Cryptosuite) which is not maintained.
If people on platformIO have more experience than the normal Arduino user, it might be usefull to disable the `C++` wrapper by default, because they will be happier without it.

**Comment by skorokithakis** [comment]
Oh, I see what you mean. I think on average they might be a bit more experienced, but I'm not very experienced myself, so I couldn't tell you. I'm not sure how you would choose between the two interfaces, maybe you can make two PlatformIO entries, or have a user-selectable switch?

**Comment by daknuett** [comment]
The user can already turn the `C++` wrapper off ([Take a look at this](https://daknuett.github.io/cryptosuite2/usage.html)). So I think I will keep it the way it is. 

Do you know what happens after registration? I cannot find the library in the PlatformIO registry yet.

**Comment by skorokithakis** [comment]
I think it needs to be approved, which takes a few hours to at most a day, they're pretty responsive. Then the library just appears and people can add it to their dependencies.
